// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action File;
    
    private Gtk.Action Open;
    
    private Gtk.Action SaveAs;
    
    private Gtk.Action Exit;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Entry txtEntry;
    
    private Gtk.Button cmdEntry;
    
    private Gtk.TextView txtConversation;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w2.Add(this.File, null);
        this.Open = new Gtk.Action("Open", Mono.Unix.Catalog.GetString("Open"), null, null);
        this.Open.ShortLabel = Mono.Unix.Catalog.GetString("Open");
        w2.Add(this.Open, null);
        this.SaveAs = new Gtk.Action("SaveAs", Mono.Unix.Catalog.GetString("Save As"), null, null);
        this.SaveAs.ShortLabel = Mono.Unix.Catalog.GetString("Save As");
        w2.Add(this.SaveAs, null);
        this.Exit = new Gtk.Action("Exit", Mono.Unix.Catalog.GetString("Exit"), null, null);
        this.Exit.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
        w2.Add(this.Exit, null);
        w1.InsertActionGroup(w2, 0);
        Gtk.ActionGroup w3 = new Gtk.ActionGroup("New Action Group");
        w1.InsertActionGroup(w3, 1);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("Persona");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        this.vbox1.Spacing = 6;
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='Open'/><menuitem action='SaveAs'/><menuitem action='Exit'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w4.Position = 0;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.txtEntry = new Gtk.Entry();
        this.txtEntry.CanFocus = true;
        this.txtEntry.Name = "txtEntry";
        this.txtEntry.IsEditable = true;
        this.txtEntry.InvisibleChar = '●';
        this.hbox1.Add(this.txtEntry);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.txtEntry]));
        w5.Position = 0;
        // Container child hbox1.Gtk.Box+BoxChild
        this.cmdEntry = new Gtk.Button();
        this.cmdEntry.CanFocus = true;
        this.cmdEntry.Name = "cmdEntry";
        this.cmdEntry.UseUnderline = true;
        this.cmdEntry.Label = Mono.Unix.Catalog.GetString("OK");
        this.hbox1.Add(this.cmdEntry);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.cmdEntry]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        this.vbox1.Add(this.hbox1);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
        w7.Position = 1;
        w7.Expand = false;
        w7.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.txtConversation = new Gtk.TextView();
        this.txtConversation.CanFocus = true;
        this.txtConversation.Name = "txtConversation";
        this.vbox1.Add(this.txtConversation);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox1[this.txtConversation]));
        w8.Position = 2;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 632;
        this.DefaultHeight = 524;
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.cmdEntry.Clicked += new System.EventHandler(this.OnCmdEntryClicked);
    }
}
